"""Copyright (c) 2024 Scott Staniewicz. All rights reserved.

synth: Synthetic data generator for InSAR time series analysis
"""

# ruff: noqa: F401
# _version.py is autogenerated by setuptools_scm
from __future__ import annotations

from synth._version import version as __version__

from ._blocks import *
from ._types import *
from .config import *

__all__ = ["__version__"]
